events {}

http {

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:8000;
        }

        location /resume/ {
            proxy_pass http://resume-service:8001;
        }

        location /jobs/ {
            proxy_pass http://job-service:8002;
        }

        location /match/ {
            proxy_pass http://matching-service:8003;
        }

        location /ai/ {
            proxy_pass http://ai-worker:8004;
        }

        location /notify/ {
            proxy_pass http://notification-service:8005;
        }

    }
}